### ISSUE TITLE
Settings Button soll zu Logout Button werden

### ISSUE THREAD

**Issue by uelca** [johannaNagel/TES_Turnierplaner#91]
Der Setting Button im Botton Navigator soll zu einem Logout Button werden, so dass ein einfacher Logout möglich ist. Wenn man auf den LogOut Button klickt, soll ein PopUp erscheinen und fragen ob man sich wirklich ausloggen will. Nach dem dies bestätigt wurde, gelangt man auf den Login Screen zum einloggen und ist somit ausgeloggt.

**Comment by johannaNagel** [comment]
Der Setting Button im Botton Navigator soll zu einem Logout Button werden, so dass ein einfacher Logout möglich ist. Wenn man auf den LogOut Button klickt, soll ein PopUp erscheinen und fragen ob man sich wirklich ausloggen will. Nach dem dies bestätigt wurde, gelangt man auf den Login Screen zum einloggen
